config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, except: [:new, :destroy] do
    resources :messages, only: [:new, :create]
  end

  resources :posts, except: [:updated, :edit, :show]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  resources :messages, only: [:index, :destroy]

  root 'posts#index'
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
  belongs_to :receiver, class_name: 'User', foreign_key: 'receiver_id'

  validates :sender_id, presence: true
  validates :receiver_id, presence: true
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :body, presence: true, length: { maximum: 140 }

  scope :feed, -> (ids) { where(user_id: ids).order("created_at DESC") } 
  scope :search, -> (term) { where("body LIKE ?", "%#{term}%") }
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :messages, class_name: "Message", foreign_key: 'receiver_id'

  has_many :favorites
  has_many :favorite_posts, through: :favorites, source: :post

  has_many :following_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :following_relationships, source: :followed

  has_many :follower_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :follower

  def following?(user)
    following_relationships.find_by(followed_id: user.id)
  end

  def follow!(user)
    following_relationships.create!(followed_id: user.id)
  end

  def unfollow!(user)
    following_relationships.find_by(followed_id: user.id).destroy
  end

  def followed_user_ids
    followed_users.pluck(:id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :html, :json
  protect_from_forgery with: :exception
  after_filter :set_csrf_cookie_for_ng

  def index
  end

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @favorites = current_user.favorites
  end
  
  def create
    if current_user.favorites.create(favorite_params)
      redirect_to posts_url, notice: 'Post has been favorited'
    else
      redirect_to posts_url, alert: 'Not able to favorite this post'
    end
  end
  
  def destroy
    if Favorite.find(params[:id]).destroy
      redirect_to posts_url, notice: 'Post has been removed from favorites'
    else
      redirect_to posts_url, notice: 'Not able to remove favorite'
    end
  end
  
  private

    def favorite_params
      params.require(:favorite).permit(:post_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_message, only: [:destroy]

  def index
    @messages = current_user.messages
  end

  def new
    @user = User.find(params[:user_id])
    @message = Message.new
  end

  def create
    user = User.find(params[:user_id])
    @message = Message.new(sender: current_user, receiver: user, body: message_params[:body])
    if @message.save
      redirect_to user, notice: 'Your message has been sent!'
    else
      render :new, notice: 'Your message failed to send.'
    end
  end

  def destroy
    if @message.destroy
      redirect_to messages_url, notice: 'Message was successfully deleted.'
    else
      redirect_to messages_url, notice: 'Not able to delete this message.'
    end
  end

  private

    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:destroy]

  def index
    @posts = Post.includes(:user).feed(current_user.followed_user_ids << current_user.id)
    @posts = @posts.search(params[:query]) if params[:query]
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to action: "index", notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end


    def post_params
      params.require(:post).permit(:body)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    if @user = User.find(params[:relationship][:followed_id])
      current_user.follow!(@user)
      redirect_to users_path, notice: "You are now following #{@user.email}."
    else
      redirect_to users_path, notice: 'Not able to follow this user.'
    end
  end

  def destroy
    if @user = Relationship.find(params[:id]).followed
      current_user.unfollow!(@user)
      redirect_to users_path, notice: "You are no longer following #{@user.email}"
    else
      redirect_to users_path, notice: 'Not able to unfollow.'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/application/index.html.erb
<div class="main-view-container" ui-view></div>

app/views/favorites/_favorite.html.erb
<%= form_for(current_user.favorites.build(post_id: post.id)) do |f| %>
  <%= f.hidden_field :post_id %>
  <%= f.submit "Favorite" %>
<% end %>

app/views/favorites/_unfavorite.html.erb
<%= form_for(current_user.favorites.find_by(post_id: post.id), method: :delete) do |f| %>
  <%= f.hidden_field :post_id %>
  <%= f.submit "Unfavorite" %>
<% end %>

app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Favorites</h1>

<% if @favorites.length > 0 %>
  <ul>
  <% @favorites.each do |favorite| %>
    <li>
      <p><%= favorite.post.body %></p>
      <span>
        Posted by <%= link_to favorite.post.user.email, user_path(favorite.post.user) %> <%= time_ago_in_words(favorite.post.created_at) %> ago.
      </span>
      <br>
      <span>
        Favorited on <%= favorite.created_at.strftime("%B %d, %Y") %>
      </span>
      <% if current_user.favorite_posts.include?(favorite.post) %>
        <%= render '/favorites/unfavorite', post: favorite.post %>
      <% else %>
        <%= render '/favorites/favorite', post: favorite.post  %>
      <% end %>
    </li>
  <% end %>
  </ul>
<% else %>
  You don't have any favorites. Click <%= link_to 'here', root_path %> to view your feed and favorite some posts.
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  <%= link_to('My Feed', root_path) %> | 
  <%= link_to('All Users', users_path) %> | 
  <%= link_to('My Profile', user_path(current_user)) %> | 
  <%= link_to('My Favorites', favorites_path) %> | 
  <%= link_to('My Inbox', messages_path) %> | 
  <%= link_to('New Post', new_post_path) %> | 
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
<% end %>
<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for [@user, @message] do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <br>
    <%= f.text_area :body, placeholder: 'Type message here' %>
  </div>
  <div class="actions">
    <%= f.submit "Send Message" %>
  </div>
<% end %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Inbox</h1>

<% if @messages.length > 0 %>
  <ul>
  <% @messages.each do |message| %>
    <li>
      <p><%= message.body %></p>
      <span>
        Sent from <%= link_to message.sender.email, user_path(message.sender) %> <%= time_ago_in_words(message.created_at) %> ago.
      </span>
      <%= link_to "Delete", message, method: :delete,
                                         title: message.body, data: {confirm: 'Are you sure you want to delete this message?'} %>
      <br>
    </li>
  <% end %>
  </ul>
<% else %>
  You don't have any messages.
<% end %>

app/views/messages/new.html.erb
<h1>New Direct Message</h1>

<%= render 'form' %>

<%= link_to 'Back', user_path(@user) %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <br>
    <%= f.text_field :body, placeholder: 'Type post here' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<li>
  <p><%= post.body %></p>
  <span>
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
  <% if current_user?(post.user) %>
    <%= link_to "Delete", post, method: :delete,
                                     title: post.body %>
  <% end %>
</li>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag posts_path, method: :get do %>
  <%= label_tag(:query, "Search") %>
  <%= text_field_tag(:query) %>
  <%= submit_tag("Search") %>
<% end %>

<h1>My Feed</h1>
<% if current_user.followed_users.count == 0 && @posts.length > 0 %>
  You aren't following any users. Click <%= link_to 'here', users_path %> to view the user list.
<% end %>
<br>
<% if @posts.length > 0 %>
  <ul>
  <% @posts.each do |post| %>
    <li>
      <p><%= post.body %></p>
      <span>
        Posted by <%= link_to post.user.email, user_path(post.user) %> <%= time_ago_in_words(post.created_at) %> ago.
      </span>
      <% if current_user?(post.user) %>
        <%= link_to "Delete", post, method: :delete,
                                         title: post.body, data: {confirm: 'Are you sure you want to delete this post?'} %>
      <% else %>
        <% if current_user.favorite_posts.include?(post) %>
          <%= render '/favorites/unfavorite', post: post %>
        <% else %>
          <%= render '/favorites/favorite', post: post  %>
        <% end %>
      <% end %>
    </li>
  <% end %>
  </ul>
<% else %>
  Your feed is empty. Click <%= link_to 'here', users_path %> to follow some users.
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(followed_id: user.id)) do |f| %>
  <%= f.hidden_field :followed_id %>
  <%= f.submit "Follow" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: user.id), method: :delete) do |f| %>
  <%= f.hidden_field :followed_id %>
  <%= f.submit "Unfollow" %>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'View', user %></td>
        <td>
          <% unless current_user?(user) %>
            <% if current_user.following?(user) %>
              <%= render 'unfollow', user: user %>
            <% else %>
              <%= render 'follow', user: user  %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @user.email %>'s Page
</h1>

<p>
  <%= link_to "Send #{@user.email} a direct message", new_user_message_path(@user) %>
</p>

<% unless current_user?(@user) %>
  <% if current_user.following?(@user) %>
    <%= render 'unfollow', user: @user %>
  <% else %>
    <%= render 'follow', user: @user %>
  <% end %>
<% end %>

<h3>Posts:</h3>

<% if @posts.length > 0 %>
  <% @posts.each do |post| %>
    <%= render '/posts/post', post: post %>
  <% end %>
<% else %>
  <p><%= @user.email %> doesn't have any posts.</p>
<% end %>